output_name: FNOporousVelocity

hydra:
  run:
    dir: ./${output_name}/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

output:
  dir: ./${output_name}

data:
  base_folder: /home/jwinter/Development/TorchLBM/cases/dataset_creation
  num_channels: 3
  normalization_mean:
  - 1.345
  - 0.0
  - 0.0
  normalization_std:
  - 1.118
  - 0.1522
  - 0.1522
  field_name: velocity

arch:
  decoder:
    out_features: ${data.num_channels}
    layers: 3
    layer_size: 256

  fno:
    in_channels: 1
    dimension: 3
    latent_channels: 64
    fno_layers: 4
    fno_modes: 20
    padding: 9

scheduler:
  initial_lr: 1.E-3
  decay_rate: .875
  decay_pseudo_epochs: 8

training:
  resolution: 256
  batch_size: 32
  rec_results_freq : 256
  max_pseudo_epochs: 512
  pseudo_epoch_sample_size: 600

validation:
  sample_size: 256
  validation_pseudo_epochs: 32
