output_name: FNOkarmanVelocity_debug

hydra:
  run:
    dir: ./${output_name}/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

output:
  dir: ./${output_name}

data:
  base_folder: ./datasets
  num_channels: 2
  normalization_mean:
  - 0.020051
  - 0.0
  normalization_std:
  - 0.0034
  - 0.0037
  field_name: velocity

arch:
  decoder:
    out_features: ${data.num_channels}
    layers: 1
    layer_size: 128

  fno:
    in_channels: ${data.num_channels}
    dimension: 2
    latent_channels: 32
    fno_layers: 5
    fno_modes: 40
    padding: 9

scheduler:
  initial_lr: 1.E-3
  decay_rate: .85
  decay_pseudo_epochs: 8

training:
  resolution: 256
  batch_size: 16
  rec_results_freq : 32 #every 32nd pseudo epoch we checkppoint the model
  max_pseudo_epochs: 128 #there will be 4 checkpoints.
  pseudo_epoch_sample_size: 2048

validation:
  sample_size: 256
  validation_pseudo_epochs: 2
